# esphome compile chris-pc.yaml
#
substitutions:
  devicename: "chris-pc"
  upper_devicename: "Chris PC"

esphome:
  name: $devicename
#  platform: HOST

# Enable logging
logger:

host:
  # eth0
  mac_address: 04:7c:16:4d:ec:12

#mdns:
#  id: mdns_mdnscomponent
#  disabled: true

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

dbus:

#web_server:
#  port: 8123

#i2c:
#  path: /dev/i2c-12

## Example configuration entry
#pca9685:
#  - id: pca9685_hub1
#    frequency: 500
##    address: 0x40

## Individual outputs
#output:
#  - platform: pca9685
#    pca9685_id: 'pca9685_hub1'
#    id: pwm0
#    inverted: true
#    channel: 0
#
#light:
#  - platform: monochromatic
#    name: "${upper_devicename} light0"
#    output: pwm0
#    gamma_correct: 1

switch:
  - name: "${upper_devicename} power standby"
    platform: template
    turn_on_action:
    - dbus.send:
        dbus_system: true
        dbus_destination: org.freedesktop.login1
        dbus_path: /org/freedesktop/login1
        dbus_interface: org.freedesktop.login1.Manager
        dbus_method: Suspend
        dbus_args: ["bool:True"]
  - name: "${upper_devicename} Amarok Play Switch"
    platform: template
    lambda: |-
      return id(playback_status).state == "Playing";
    id: amarok_switch
    optimistic: true
    restore_mode: DISABLED
    turn_on_action:
    - logger.log: "Switch Turned On!"
    # dbus-send --session --print-reply --dest=org.mpris.MediaPlayer2.amarok /org/mpris/MediaPlayer2 org.mpris.MediaPlayer2.Player.Play
    - dbus.send:
        dbus_destination: org.mpris.MediaPlayer2.amarok
        dbus_path: /org/mpris/MediaPlayer2
        dbus_interface: org.mpris.MediaPlayer2.Player
        # dbus_method: PlayPause
        dbus_method: Play
        dbus_args: []
    turn_off_action:
    - logger.log: "Switch Turned Off!"
    - dbus.send:
        dbus_destination: org.mpris.MediaPlayer2.amarok
        dbus_path: /org/mpris/MediaPlayer2
        dbus_interface: org.mpris.MediaPlayer2.Player
        dbus_method: Stop
        dbus_args: []


  - name: "${upper_devicename} Screen Lock"
    # lock unlock via dbus
    # other method: loginctl
    platform: template
    lambda: |-
      return id(lock_active).state == "true";
    # id: lock_switch
    optimistic: true
    restore_mode: DISABLED
    turn_on_action:
    - logger.log: "Lock Switch Turned On!"
    # dbus-send --session --print-reply --dest=org.freedesktop.ScreenSaver /ScreenSaver org.freedesktop.ScreenSaver.Lock
    - dbus.send:
        dbus_destination: org.freedesktop.ScreenSaver 
        dbus_path: /ScreenSaver
        dbus_interface: org.freedesktop.ScreenSaver
        dbus_method: Lock
        dbus_args: []
    turn_off_action:
    - logger.log: "Switch Turned Off!"
    - dbus.send:
        dbus_destination: org.freedesktop.ScreenSaver 
        dbus_path: /ScreenSaver
        dbus_interface: org.freedesktop.ScreenSaver
        dbus_method: Unlock
        dbus_args: []



# mit qdbusviewer-qt5 schaun
# dbus-send --session --print-reply --dest=org.mpris.MediaPlayer2.amarok /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'Metadata'
text_sensor:
#  - !include common/base-text-sensor-version.yaml

  - platform: "dbus"
    dbus_destination: "org.mpris.MediaPlayer2.amarok"
    dbus_path: "/org/mpris/MediaPlayer2"
    dbus_interface: "org.freedesktop.DBus.Properties"
    dbus_method: Get
    dbus_args:
      - "org.mpris.MediaPlayer2.Player"
      - "Metadata"
    name: "${upper_devicename} amarok title, artist"
    icon: "mdi:cube-outline"
    property_separator: ' - '
    properties:
      - "xesam:artist"
      - "xesam:title"

  # dbus-send --print-reply --dest=org.mpris.MediaPlayer2.amarok /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus'
  - platform: dbus
    dbus_destination: org.mpris.MediaPlayer2.amarok
    dbus_path: /org/mpris/MediaPlayer2
    dbus_method: Get
    dbus_interface: org.freedesktop.DBus.Properties
    dbus_args:
      - org.mpris.MediaPlayer2.Player
      - PlaybackStatus
    name: "${upper_devicename} amarok status"
    icon: mdi:cube-outline
    properties:
      - "PlaybackStatus"
    id: playback_status

  # dbus-send --session --print-reply --dest=org.freedesktop.ScreenSaver --type=method_call /org/freedesktop/ScreenSaver org.freedesktop.ScreenSaver.GetActive
  - platform: dbus
    dbus_destination: org.freedesktop.ScreenSaver
    dbus_path: /org/freedesktop/ScreenSaver
    dbus_interface: org.freedesktop.ScreenSaver
    dbus_method: GetActive
    dbus_args: []
    name: "${upper_devicename} lock status"
    properties: ["root"]
    id: lock_active

  # smart register !!! nur von sata platten
  # gdbus call --system --dest org.freedesktop.UDisks2 --object-path "/org/freedesktop/UDisks2/drives/WDC_WD40EFRX_68N32N0_WD_WCC7K1PK3U4A" --method "org.freedesktop.UDisks2.Drive.Ata.SmartGetAttributes" '{}' 

#  - platform: host_filesystem
#    sda:
#      name: "${upper_devicename} sda"

#sensor:
#  - platform: vl53l0x
#    name: "${upper_devicename} VL53L0x Distance"
#    address: 0x29
#    update_interval: 10s
#    long_range: true
#    timeout: 50ms
