substitutions:
  devicename: "rc522"
  upper_devicename: "RC522"

esphome:
  name: "${devicename}"
  platform: ESP8266
  #board: esp01
  #board: nodemcuv2
  board: nodemcu

<<: !include common/base.yaml

spi:
#  clk_pin: D5
#  mosi_pin: D7
#  miso_pin: D6
  clk_pin: GPIO14
  mosi_pin: GPIO13
  miso_pin: GPIO12

rc522_spi:
#  cs_pin: D8
#  reset_pin: D4
  cs_pin: GPIO15
  reset_pin: GPIO2
  on_tag:
    then:
      - homeassistant.tag_scanned: !lambda 'return x;'

binary_sensor:
  - !include common/base-binarysensor-status.yaml
#  - platform: gpio
#    pin:
#      number: GPIO13
#      mode: INPUT_PULLUP
#      inverted: True
#    # name: "${devicename} - Schalter Status"
#    id: "${devicename}_button_state"
#  - platform: gpio
#    pin: GPIO03
#    name: ${upper_devicename} input
#    device_class: motion
#  - platform: rc522
#    uid: 74-10-37-94
#    name: "RC522 RFID Tag"

sensor:
  - !include common/base-sensor-wifi.yaml
  - !include common/base-sensor-uptime.yaml
  - !include common/base-sensor-vcc.yaml

switch:
  - !include common/base-switch-reset.yaml

light:
#  - platform: binary
  - platform: monochromatic
    name: "${upper_devicename} out1"
    output: 'gpio_out1'
#  - platform: binary
#  - platform: monochromatic
#    name: "${upper_devicename} out2"
#    output: 'gpio_out2'

output:
#  - platform: gpio
  - platform: esp8266_pwm
    pin: GPIO00
    inverted: true
    id: gpio_out1
#  - platform: esp8266_pwm
#    pin: GPIO02
#    inverted: true
#    id: gpio_out2




