#
# GPIO16 - OTA switch lötpad, 10k pull up auf +3,3V
# GPIO0 - S1 lötppad rechts
#
substitutions:
  # steckdose Lüftung Terrasse
  devicename: "sonoff_d1"
  upper_devicename: "Sonoff D1 Dimmer"
  # minimum wattage to mark consumer as active
  # consumer_min_wattage: "10"

esphome:
  name: $devicename
  comment: $upper_devicename
  # platform: ESP8266
  # board: esp8285
#  on_boot:
#    - light.turn_on:
#        id: light_1
#        brightness: 1%

esp8266:
  board: esp8285
  restore_from_flash: true

<<: !include common/base.yaml

# logs off
logger:
  baud_rate: 0

uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600

switch:
  - !include common/base-switch-reset.yaml

binary_sensor:
  - !include common/base-binarysensor-status.yaml

sensor:
  - !include common/base-sensor-wifi.yaml
  - !include common/base-sensor-uptime.yaml

light:
  - platform: sonoff_d1
    use_rm433_remote: False
    name: "${devicename} Output"
    restore_mode: ALWAYS_OFF
    gamma_correct: 0.0
    default_transition_length: 1s
    min_value: 0
    id: light_1
  - platform: status_led
    name: "${devicename} blue led"
    pin:
      number: GPIO13
      inverted: true

