networks:
- ssid: !secret wifi_name
  password: !secret wifi_pass
  # connect to first/hidden wifi
  #fast_connect:
  #  on
  hidden: false

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#ap:
#  ssid: "${upper_devicename} Fallback Hotspot"
#  password: !secret wifi_pass

# 20210518 hatta mit esp8266 ned wolln
#captive_portal:

# flash IP adress
# HINT: es gibt auch ein esphome rename ....
#use_address: 192.168.178.188

